### ISSUE TITLE
Ittichoat Ongsritrakul

### ISSUE THREAD

**Issue by ittichoat** [tonmanna/ElmQuizzProject#1]
function FizzBuzz(value) {
	if (value % 3 == 0 && value % 5 == 0) {
		return 'Fizz Buzz'
	} else if (value % 3 == 0) {
		return 'Fizz'
	} else if (value % 5 == 0) {
		return 'Buzz'
	}
	return value
}

function main() {
	for (i = 0; i <= 1000000; i++) {
		console.log(FizzBuzz(i))
	}
}

main()

----------------------------------------------------------------------------------------
1.20
2.apple
  banana
  orange
  strawberry
3.0
4.12
5..toLowerCase()
6.\n
7.amazing apple
amazing banana
amazing strawberry
8.banana
strawberry
9.
10.ตอนเริ่มรัน จะพิม Fetching ออกมา แล้วต่อไปจะทำการรอ fetchUserData() จนเสร็จสิ้นจึงจะไปพิม Fetched
async จะทำให้ทำงานไปพร้อมกัน แต่พอมี await จึงจำเป็นจะต้องรอให้ await ทำงานให้เสร็จสิ้นก่อนจึงจะไปทำงานตัวต่อไป

**Comment by tonmanna** [comment]
ขอบคุณมากครับ
